# Generated by Django 5.1.1 on 2025-07-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=15)),
                ('destination', models.CharField(max_length=500)),
                ('members', models.PositiveIntegerField()),
                ('date_from', models.DateField()),
                ('date_upto', models.DateField()),
                ('suggestion', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='pending', max_length=10)),
            ],
        ),
    ]
