# Generated by Django 5.1.1 on 2025-07-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_package_customer_package'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('user_type', models.CharField(choices=[('Driver', 'Driver'), ('Owner', 'Owner')], max_length=10)),
                ('device_token', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
    ]
